/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package implicitForms;

/**
 *
 * @author Robert Walker
 */
public class announcePanel extends javax.swing.JPanel {

    /**
     * Creates new form twoStimulusPanel
     */
    public announcePanel() {
        initComponents();
    }
    
    public announcePanel(String message) {
        initComponents();
        lbl_Announcement.setText(message);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Announcement = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        lbl_Announcement.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Announcement.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Announcement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Announcement.setText("jLabel7");
        lbl_Announcement.setName("4"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Announcement, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(lbl_Announcement, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addGap(110, 110, 110))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_Announcement;
    // End of variables declaration//GEN-END:variables
}
