/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package implicitForms;

import implicit.Stimulus;
import implicit.experimentView;
import implicit.implicitAssociationXMLWriter;
import java.awt.Component;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Robert Walker
 */
public class configForm extends javax.swing.JFrame {
    
        Component labelFind[];
        Stimulus configStimuli[] = new Stimulus[5];
        List<experimentView> expViews = new ArrayList<>();
        int sharedCursor;
        public static String twoPanel = "Two Stimulus Panel";
        public static String fourPanel = "Four Stimulus Panel";
        public static String announcePanel = "Announcement Panel";
        String oldPath = System.getProperty("user.dir");
        
    /**
     * Creates new form configForm
     */
    public configForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_PanelNo = new javax.swing.JLabel();
        lbl_PanelType = new javax.swing.JLabel();
        cbo_PanelType = new javax.swing.JComboBox();
        fld_PanelNo = new javax.swing.JLabel();
        btn_PreviousSlide = new javax.swing.JButton();
        btn_NextSlide = new javax.swing.JButton();
        btn_Confirm = new javax.swing.JButton();
        pnl_LeftTop = new javax.swing.JPanel();
        btn_AddText_lt = new javax.swing.JButton();
        btn_AddPic_lt = new javax.swing.JButton();
        lbl_StimulusDisplay_lt = new javax.swing.JLabel();
        pnl_LeftBottom = new javax.swing.JPanel();
        btn_AddText_lb = new javax.swing.JButton();
        btn_AddPic_lb = new javax.swing.JButton();
        lbl_StimulusDisplay_lb = new javax.swing.JLabel();
        pnl_RightTop = new javax.swing.JPanel();
        btn_AddText_rt = new javax.swing.JButton();
        btn_AddPic_rt = new javax.swing.JButton();
        lbl_StimulusDisplay_rt = new javax.swing.JLabel();
        pnl_RightBottom = new javax.swing.JPanel();
        btn_AddText_rb = new javax.swing.JButton();
        btn_AddPic_rb = new javax.swing.JButton();
        lbl_StimulusDisplay_rb = new javax.swing.JLabel();
        pnl_Focus = new javax.swing.JPanel();
        btn_AddText_f = new javax.swing.JButton();
        btn_AddPic_f = new javax.swing.JButton();
        lbl_StimulusDisplay_f = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbo_CorrectSide = new javax.swing.JComboBox();
        btn_SaveChanges = new javax.swing.JButton();
        lbl_ConfigName = new javax.swing.JLabel();
        txt_ConfigName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Config Screen");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        lbl_PanelNo.setText("Panel No");

        lbl_PanelType.setLabelFor(cbo_PanelType);
        lbl_PanelType.setText("PanelType");

        cbo_PanelType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Two Stimulus Panel", "Four Stimulus Panel", "Announcement Panel" }));
        cbo_PanelType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_PanelTypeActionPerformed(evt);
            }
        });

        fld_PanelNo.setText("1");

        btn_PreviousSlide.setText("Previous Slide");

        btn_NextSlide.setText("Next Slide/Add");
        btn_NextSlide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NextSlideActionPerformed(evt);
            }
        });

        btn_Confirm.setText("Complete");
        btn_Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConfirmActionPerformed(evt);
            }
        });

        pnl_LeftTop.setBackground(new java.awt.Color(153, 153, 153));
        pnl_LeftTop.setBorder(javax.swing.BorderFactory.createTitledBorder("Left Top Stimulus"));
        pnl_LeftTop.setName(experimentView.LEFT_TOP_INDEX + "");

        btn_AddText_lt.setText("Add Text");
        btn_AddText_lt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddText_ltActionPerformed(evt);
            }
        });

        btn_AddPic_lt.setText("Add Picture");
        btn_AddPic_lt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddPic_ltActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_LeftTopLayout = new javax.swing.GroupLayout(pnl_LeftTop);
        pnl_LeftTop.setLayout(pnl_LeftTopLayout);
        pnl_LeftTopLayout.setHorizontalGroup(
            pnl_LeftTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_LeftTopLayout.createSequentialGroup()
                .addComponent(btn_AddText_lt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btn_AddPic_lt))
            .addComponent(lbl_StimulusDisplay_lt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnl_LeftTopLayout.setVerticalGroup(
            pnl_LeftTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_LeftTopLayout.createSequentialGroup()
                .addComponent(lbl_StimulusDisplay_lt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_LeftTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_AddText_lt)
                    .addComponent(btn_AddPic_lt)))
        );

        pnl_LeftBottom.setBackground(new java.awt.Color(153, 153, 153));
        pnl_LeftBottom.setBorder(javax.swing.BorderFactory.createTitledBorder("Left Bottom Stimulus"));
        pnl_LeftBottom.setName(experimentView.LEFT_BOTTOM_INDEX+"");

        btn_AddText_lb.setText("Add Text");
        btn_AddText_lb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddText_lbActionPerformed(evt);
            }
        });

        btn_AddPic_lb.setText("Add Picture");
        btn_AddPic_lb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddPic_lbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_LeftBottomLayout = new javax.swing.GroupLayout(pnl_LeftBottom);
        pnl_LeftBottom.setLayout(pnl_LeftBottomLayout);
        pnl_LeftBottomLayout.setHorizontalGroup(
            pnl_LeftBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_LeftBottomLayout.createSequentialGroup()
                .addComponent(btn_AddText_lb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_AddPic_lb))
            .addComponent(lbl_StimulusDisplay_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnl_LeftBottomLayout.setVerticalGroup(
            pnl_LeftBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_LeftBottomLayout.createSequentialGroup()
                .addComponent(lbl_StimulusDisplay_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_LeftBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_AddText_lb)
                    .addComponent(btn_AddPic_lb)))
        );

        pnl_RightTop.setBackground(new java.awt.Color(153, 153, 153));
        pnl_RightTop.setBorder(javax.swing.BorderFactory.createTitledBorder("Right Top Stimulus"));
        pnl_RightTop.setName(experimentView.RIGHT_TOP_INDEX+"");

        btn_AddText_rt.setText("Add Text");
        btn_AddText_rt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddText_rtActionPerformed(evt);
            }
        });

        btn_AddPic_rt.setText("Add Picture");
        btn_AddPic_rt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddPic_rtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_RightTopLayout = new javax.swing.GroupLayout(pnl_RightTop);
        pnl_RightTop.setLayout(pnl_RightTopLayout);
        pnl_RightTopLayout.setHorizontalGroup(
            pnl_RightTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_RightTopLayout.createSequentialGroup()
                .addComponent(btn_AddText_rt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_AddPic_rt))
            .addComponent(lbl_StimulusDisplay_rt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnl_RightTopLayout.setVerticalGroup(
            pnl_RightTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_RightTopLayout.createSequentialGroup()
                .addComponent(lbl_StimulusDisplay_rt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_RightTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_AddText_rt)
                    .addComponent(btn_AddPic_rt)))
        );

        pnl_RightBottom.setBackground(new java.awt.Color(153, 153, 153));
        pnl_RightBottom.setBorder(javax.swing.BorderFactory.createTitledBorder("Right Bottom Stimulus"));
        pnl_RightBottom.setName(experimentView.RIGHT_BOTTOM_INDEX+"");

        btn_AddText_rb.setText("Add Text");
        btn_AddText_rb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddText_rbActionPerformed(evt);
            }
        });

        btn_AddPic_rb.setText("Add Picture");
        btn_AddPic_rb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddPic_rbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_RightBottomLayout = new javax.swing.GroupLayout(pnl_RightBottom);
        pnl_RightBottom.setLayout(pnl_RightBottomLayout);
        pnl_RightBottomLayout.setHorizontalGroup(
            pnl_RightBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_RightBottomLayout.createSequentialGroup()
                .addComponent(btn_AddText_rb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_AddPic_rb))
            .addComponent(lbl_StimulusDisplay_rb, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnl_RightBottomLayout.setVerticalGroup(
            pnl_RightBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_RightBottomLayout.createSequentialGroup()
                .addComponent(lbl_StimulusDisplay_rb, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_RightBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_AddText_rb)
                    .addComponent(btn_AddPic_rb)))
        );

        pnl_Focus.setBackground(new java.awt.Color(153, 153, 153));
        pnl_Focus.setBorder(javax.swing.BorderFactory.createTitledBorder("Focus Stimulus"));
        pnl_Focus.setName(experimentView.FOCUS_INDEX+"");

        btn_AddText_f.setText("Add Text");
        btn_AddText_f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddText_fActionPerformed(evt);
            }
        });

        btn_AddPic_f.setText("Add Picture");
        btn_AddPic_f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddPic_fActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_FocusLayout = new javax.swing.GroupLayout(pnl_Focus);
        pnl_Focus.setLayout(pnl_FocusLayout);
        pnl_FocusLayout.setHorizontalGroup(
            pnl_FocusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_FocusLayout.createSequentialGroup()
                .addComponent(btn_AddText_f)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_AddPic_f))
            .addComponent(lbl_StimulusDisplay_f, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnl_FocusLayout.setVerticalGroup(
            pnl_FocusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_FocusLayout.createSequentialGroup()
                .addComponent(lbl_StimulusDisplay_f, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_FocusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_AddText_f)
                    .addComponent(btn_AddPic_f)))
        );

        jLabel1.setText("Correct Side");

        cbo_CorrectSide.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Left", "Right" }));

        btn_SaveChanges.setText("Save Panel");
        btn_SaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveChangesActionPerformed(evt);
            }
        });

        lbl_ConfigName.setText("Configuration Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btn_PreviousSlide)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_NextSlide)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Confirm))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_ConfigName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ConfigName))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_PanelNo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fld_PanelNo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_PanelType)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbo_PanelType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbo_CorrectSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pnl_LeftTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(pnl_RightTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pnl_LeftBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pnl_RightBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(121, 121, 121)
                                        .addComponent(pnl_Focus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_SaveChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_PanelNo)
                    .addComponent(fld_PanelNo)
                    .addComponent(lbl_PanelType)
                    .addComponent(cbo_PanelType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cbo_CorrectSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ConfigName)
                    .addComponent(txt_ConfigName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_RightTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_LeftTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_LeftBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_RightBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_Focus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_SaveChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_PreviousSlide)
                    .addComponent(btn_NextSlide)
                    .addComponent(btn_Confirm))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbo_PanelTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_PanelTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_PanelTypeActionPerformed

    private void btn_AddText_ltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddText_ltActionPerformed
        
        addStimulusTextbyButton((JButton) evt.getSource());
             
    }//GEN-LAST:event_btn_AddText_ltActionPerformed

    private void btn_AddPic_ltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddPic_ltActionPerformed
        
        addStimulusPicbyButton((JButton) evt.getSource());
    }//GEN-LAST:event_btn_AddPic_ltActionPerformed

    private void btn_AddText_rtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddText_rtActionPerformed
        addStimulusTextbyButton((JButton) evt.getSource());
    }//GEN-LAST:event_btn_AddText_rtActionPerformed

    private void btn_AddPic_rtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddPic_rtActionPerformed
        addStimulusPicbyButton((JButton) evt.getSource());
    }//GEN-LAST:event_btn_AddPic_rtActionPerformed

    private void btn_AddText_lbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddText_lbActionPerformed
        addStimulusTextbyButton((JButton) evt.getSource());
    }//GEN-LAST:event_btn_AddText_lbActionPerformed

    private void btn_AddPic_lbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddPic_lbActionPerformed
        addStimulusPicbyButton((JButton) evt.getSource());
    }//GEN-LAST:event_btn_AddPic_lbActionPerformed

    private void btn_AddText_rbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddText_rbActionPerformed
        addStimulusTextbyButton((JButton) evt.getSource());
    }//GEN-LAST:event_btn_AddText_rbActionPerformed

    private void btn_AddPic_rbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddPic_rbActionPerformed
        addStimulusPicbyButton((JButton) evt.getSource());
    }//GEN-LAST:event_btn_AddPic_rbActionPerformed

    private void btn_AddText_fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddText_fActionPerformed
        addStimulusTextbyButton((JButton) evt.getSource());
    }//GEN-LAST:event_btn_AddText_fActionPerformed

    private void btn_AddPic_fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddPic_fActionPerformed
        addStimulusPicbyButton((JButton) evt.getSource());
    }//GEN-LAST:event_btn_AddPic_fActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        
        sharedCursor = 0;
        expViews.add(new experimentView(null, 0, true));
        fld_PanelNo.setText((sharedCursor + 1)+"");
    }//GEN-LAST:event_formComponentShown

    private void btn_SaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveChangesActionPerformed
        saveCurrentView();        
    }//GEN-LAST:event_btn_SaveChangesActionPerformed

    private void btn_NextSlideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NextSlideActionPerformed
        saveCurrentView();
        sharedCursor++;
        expViews.add(new experimentView(null, 0, true));
        fld_PanelNo.setText((sharedCursor + 1)+"");
        clearForm();
    }//GEN-LAST:event_btn_NextSlideActionPerformed

    private void btn_ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConfirmActionPerformed
        
        saveCurrentView();
        writeConfig();
        
        
    }//GEN-LAST:event_btn_ConfirmActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed
    
     private void addStimulusTextbyButton(JButton buttonPressed)
    {
        //prompt the user to enter the words that they want to use to assign the stimulus
        String stimulusMessage = JOptionPane.showInputDialog("Enter the message that you want to show for the Stimulus.");
        
        //Create the Stimulus object with the messge that was entered
        configStimuli[Integer.parseInt(buttonPressed.getParent().getName())] = new Stimulus(stimulusMessage, true);
        
        //display the result on the label
        getDisplayLabel(buttonPressed).setText(stimulusMessage);
    }
    
    private void addStimulusPicbyButton(JButton buttonPressed)
    {
        String filePath;
        JFileChooser selectPic = new JFileChooser(oldPath);
        int chooserReturn;
        File selectedPic;
        BufferedImage stimulusImage;			
        JLabel displayLabel = getDisplayLabel(buttonPressed);
        
        //show a file chooser for the picture       
        chooserReturn = selectPic.showDialog(this, "Add");
        
        //handle the result of the dialog, if the user cancels just exit
        if (chooserReturn == JFileChooser.APPROVE_OPTION )
            {
              selectedPic = selectPic.getSelectedFile();
              try {
                  filePath = selectedPic.getCanonicalPath();
              }
              catch (IOException e)  {
                    JOptionPane.showMessageDialog(rootPane, "Error Accessing File");return;
              }
              
              configStimuli[Integer.parseInt(buttonPressed.getParent().getName())] = new Stimulus(filePath, false);
                   try {
                        stimulusImage = ImageIO.read(selectedPic);
                        displayLabel.setIcon(new ImageIcon(scaleImageToLabel(stimulusImage, displayLabel)));
                       } 
                   catch (IOException e) 
                   {
                       JOptionPane.showMessageDialog(rootPane, "Not a valid picture");
                   }
               oldPath = selectedPic.getParent();
            }
    }
    
    private JLabel getDisplayLabel(Component observedComponent)
    {
        labelFind = observedComponent.getParent().getComponents();
        JLabel targetLabel;
        
        for (Component c : labelFind)
        {
            if( c instanceof JLabel )
            {
               targetLabel = (JLabel) c;
               return targetLabel;
            }
        }
        return null;
    }
    
    void writeConfig()
    {
        //create a new xml writer object    
        implicitAssociationXMLWriter.writeImplicitAssociationXML(expViews, txt_ConfigName.getText());
    }
    
    void saveCurrentView()
    {  
        int sideSelected = cbo_CorrectSide.getSelectedIndex();
        int typePanel;
        boolean correctSide;
        
        typePanel = cbo_PanelType.getSelectedIndex();
                
        if ( sideSelected == 0 ) {correctSide = true;} else {
            correctSide = false;
          }
        expViews.set(sharedCursor, new experimentView(configStimuli, typePanel, correctSide ));
    }

    
    
    
    
    private void clearForm()
    {
        lbl_StimulusDisplay_f.setText("");
        lbl_StimulusDisplay_lb.setText("");
        lbl_StimulusDisplay_lt.setText("");
        lbl_StimulusDisplay_rb.setText("");
        lbl_StimulusDisplay_rt.setText("");
        lbl_StimulusDisplay_f.setIcon(null);
        lbl_StimulusDisplay_lb.setIcon(null);
        lbl_StimulusDisplay_lt.setIcon(null);
        lbl_StimulusDisplay_rb.setIcon(null);
        lbl_StimulusDisplay_rt.setIcon(null);
    }
    
    private BufferedImage scaleImageToLabel (BufferedImage img, JLabel newScale)
    {
        //initialize original and destination dimensions
        int originalW = img.getWidth();
        int originalH = img.getHeight();
        int scaleW = newScale.getWidth();
        int scaleH = newScale.getHeight();
        
        //calculate the ratios needed to scale either the height or the width
        double xScaleFactor = ((double) scaleW) / originalW;
        double yScaleFactor = ((double) scaleH) / originalH;
        double scaleFactor = Math.min(xScaleFactor, yScaleFactor);
        int picWidth = (int)(scaleFactor * originalW);
        int picHeight = (int)(scaleFactor * originalH);
        
        //calculate the coordinate positions needed to center the image on the label surface
        int picXOrigin = (scaleW - picWidth)/2;
        int picYOrigin = (scaleH - picHeight)/2;
        
        //create a new image object to hold the scaled image, we will draw it using a Graphics2D object
        BufferedImage scaledImage = new BufferedImage(scaleW, scaleH, img.getType());
        Graphics2D imgDraw = scaledImage.createGraphics();
        imgDraw.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        
        //paint the label background and the picture file on the new image
        imgDraw.setBackground(newScale.getBackground());
        imgDraw.clearRect(0, 0, scaleW, scaleH);
        imgDraw.drawImage(img, picXOrigin, picYOrigin, picWidth, picHeight, null);
        imgDraw.dispose();
                       
        return scaledImage;
	}
   
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AddPic_f;
    private javax.swing.JButton btn_AddPic_lb;
    private javax.swing.JButton btn_AddPic_lt;
    private javax.swing.JButton btn_AddPic_rb;
    private javax.swing.JButton btn_AddPic_rt;
    private javax.swing.JButton btn_AddText_f;
    private javax.swing.JButton btn_AddText_lb;
    private javax.swing.JButton btn_AddText_lt;
    private javax.swing.JButton btn_AddText_rb;
    private javax.swing.JButton btn_AddText_rt;
    private javax.swing.JButton btn_Confirm;
    private javax.swing.JButton btn_NextSlide;
    private javax.swing.JButton btn_PreviousSlide;
    private javax.swing.JButton btn_SaveChanges;
    private javax.swing.JComboBox cbo_CorrectSide;
    private javax.swing.JComboBox cbo_PanelType;
    private javax.swing.JLabel fld_PanelNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_ConfigName;
    private javax.swing.JLabel lbl_PanelNo;
    private javax.swing.JLabel lbl_PanelType;
    private javax.swing.JLabel lbl_StimulusDisplay_f;
    private javax.swing.JLabel lbl_StimulusDisplay_lb;
    private javax.swing.JLabel lbl_StimulusDisplay_lt;
    private javax.swing.JLabel lbl_StimulusDisplay_rb;
    private javax.swing.JLabel lbl_StimulusDisplay_rt;
    private javax.swing.JPanel pnl_Focus;
    private javax.swing.JPanel pnl_LeftBottom;
    private javax.swing.JPanel pnl_LeftTop;
    private javax.swing.JPanel pnl_RightBottom;
    private javax.swing.JPanel pnl_RightTop;
    private javax.swing.JTextField txt_ConfigName;
    // End of variables declaration//GEN-END:variables
}
