/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package implicitForms;

import implicit.experimentView;
import implicit.implicitAssociationXMLReader;
import implicit.implicitTestRun;
import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Robert Walker
 */
public class testStartForm extends javax.swing.JFrame {
    
    implicitAssociationXMLReader reader;
    File configXMLFile;
    String viewPath = System.getProperty("user.dir");
    String configFileName = null;
    String configName=null;
    String participantID=null, participantName=null;
    implicitTestRun experiment;
    String DEFAULT_CONFIG_FILE_TEXT = "<<Select A Configuration File>>";
    
    /**
     * Creates new form testStartForm
     */
    public testStartForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(150, 300), new java.awt.Dimension(150, 300), new java.awt.Dimension(150, 9999));
        pnl_ConfigProperties = new javax.swing.JPanel();
        lbl_ParticipantID = new javax.swing.JLabel();
        lbl_ParticipantName = new javax.swing.JLabel();
        lbl_ConfigSelect = new javax.swing.JLabel();
        lbl_ConfigFile = new javax.swing.JLabel();
        txt_ParticipantID = new javax.swing.JTextField();
        txt_ParticipantName = new javax.swing.JTextField();
        btn_StartTest = new javax.swing.JButton();
        btn_SelectConfig = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(250, 200));
        setName("frm_testStart"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        filler2.setBackground(new java.awt.Color(0, 0, 153));
        filler2.setOpaque(true);
        getContentPane().add(filler2);

        lbl_ParticipantID.setText("Participant ID");

        lbl_ParticipantName.setText("Participant Name");

        lbl_ConfigSelect.setText("Select Configuration File");

        lbl_ConfigFile.setBackground(new java.awt.Color(255, 255, 255));
        lbl_ConfigFile.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lbl_ConfigFile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ConfigFile.setText(DEFAULT_CONFIG_FILE_TEXT);
        lbl_ConfigFile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lbl_ConfigFile.setOpaque(true);

        btn_StartTest.setText("Start Test");
        btn_StartTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_StartTestActionPerformed(evt);
            }
        });

        btn_SelectConfig.setText("Select");
        btn_SelectConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SelectConfigActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_ConfigPropertiesLayout = new javax.swing.GroupLayout(pnl_ConfigProperties);
        pnl_ConfigProperties.setLayout(pnl_ConfigPropertiesLayout);
        pnl_ConfigPropertiesLayout.setHorizontalGroup(
            pnl_ConfigPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ConfigPropertiesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_ConfigPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_ParticipantID)
                    .addComponent(lbl_ParticipantName)
                    .addComponent(lbl_ConfigSelect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_ConfigPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_ParticipantID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_ConfigPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_StartTest, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnl_ConfigPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnl_ConfigPropertiesLayout.createSequentialGroup()
                                .addComponent(lbl_ConfigFile, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_SelectConfig))
                            .addComponent(txt_ParticipantName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pnl_ConfigPropertiesLayout.setVerticalGroup(
            pnl_ConfigPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ConfigPropertiesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_ConfigPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ConfigPropertiesLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(txt_ParticipantName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_ConfigPropertiesLayout.createSequentialGroup()
                        .addComponent(lbl_ParticipantID)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_ParticipantName))
                    .addComponent(txt_ParticipantID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_ConfigPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ConfigSelect)
                    .addComponent(lbl_ConfigFile)
                    .addComponent(btn_SelectConfig))
                .addGap(26, 26, 26)
                .addComponent(btn_StartTest)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        getContentPane().add(pnl_ConfigProperties);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SelectConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SelectConfigActionPerformed
        configXMLFile = selectConfigFile();
        
        //if the select config file function returns null the button is rendered a no-op
        if ( configXMLFile !=null)
        {
         try{
                configFileName = configXMLFile.getCanonicalPath();
                lbl_ConfigFile.setText(configXMLFile.getName());
            }
            catch (IOException e) { JOptionPane.showMessageDialog(this, "Error Opening Config File");}
        }
        
        
    }//GEN-LAST:event_btn_SelectConfigActionPerformed

    private void btn_StartTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_StartTestActionPerformed
        
        List<experimentView> testViews;
        participantID = txt_ParticipantID.getText();
        participantName = txt_ParticipantName.getText();
        reader = new implicitAssociationXMLReader();
        
        if (validateFormCompletion())
        {
            //use the file name selected by the user
            testViews = reader.readImplicitAssociationXML(configFileName);
            configName = reader.nameConfig;
            
            try {
                    experiment = new implicitTestRun(configName, participantID, participantName, testViews);
                    dispose();
                }   
            catch (IOException e) {JOptionPane.showMessageDialog(this, "File Error Creating Experiment");}
                        
            //dispose of the current window after the test is ready
            dispose();
        }
        else {JOptionPane.showMessageDialog(this, "Error: One or more fields are blank");}
    }//GEN-LAST:event_btn_StartTestActionPerformed
  
    private File selectConfigFile()
    {
        JFileChooser selectConfig = new JFileChooser(viewPath);
        int chooserReturn;
               
        chooserReturn = selectConfig.showDialog(this, "Select");
        
        //handle the result of the dialog, if the user cancels just exit
        if (chooserReturn == JFileChooser.APPROVE_OPTION ) {
            viewPath = selectConfig.getSelectedFile().getParent();
            return selectConfig.getSelectedFile();
        }else {return null;}
    }
    
    private boolean validateFormCompletion()
    {
        boolean fieldsInitialized = (configFileName != null) && (participantID !=null) && (participantName!=null);
        boolean fieldsNotBlank = !(configFileName.equals("") && participantID.equals("") && participantName.equalsIgnoreCase(""));
                
        return  fieldsInitialized & fieldsNotBlank;
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_SelectConfig;
    private javax.swing.JButton btn_StartTest;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel lbl_ConfigFile;
    private javax.swing.JLabel lbl_ConfigSelect;
    private javax.swing.JLabel lbl_ParticipantID;
    private javax.swing.JLabel lbl_ParticipantName;
    private javax.swing.JPanel pnl_ConfigProperties;
    private javax.swing.JTextField txt_ParticipantID;
    private javax.swing.JTextField txt_ParticipantName;
    // End of variables declaration//GEN-END:variables
}
